[project]
name = "multimodal-knowledge-assistant"
version = "0.1.0"
description = "Minimal backend skeleton for the Multimodal Knowledge Assistant (v0.1)"
requires-python = ">=3.10"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
